BEGIN TRANSACTION;
DROP TABLE IF EXISTS "bi_list";
CREATE TABLE "bi_list" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"TP_ID"	INTEGER NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("TP_ID") REFERENCES "tp_list"("ID")
);
DROP TABLE IF EXISTS "st_list";
CREATE TABLE "st_list" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"f_name"	TEXT NOT NULL,
	"l_name"	TEXT NOT NULL,
	"n_masar"	TEXT NOT NULL UNIQUE,
	"st_id"	TEXT NOT NULL UNIQUE,
	"bi_id"	INTEGER NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("bi_id") REFERENCES "bi_list"("ID")
);
DROP TABLE IF EXISTS "tp_list";
CREATE TABLE "tp_list" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT NOT NULL,
	"visibility"	TEXT NOT NULL DEFAULT 'FALSE',
	"sheet_id"	INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
COMMIT;
