BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "bi_list" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"TP_ID"	INTEGER NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("TP_ID") REFERENCES "tp_list"("ID")
);
CREATE TABLE IF NOT EXISTS "st_list" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT NOT NULL,
	"masar"	TEXT NOT NULL,
	"ed"	TEXT NOT NULL,
	"bi_id"	INTEGER NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("bi_id") REFERENCES "bi_list"("ID")
);
CREATE TABLE IF NOT EXISTS "tp_list" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT NOT NULL UNIQUE,
	"visibility"	TEXT NOT NULL DEFAULT 'FALSE',
	"sheet_id"	INTEGER NOT NULL,
	"admin_id"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TRIGGER remove_the_rest_of_bi
BEFORE delete 
ON tp_list
BEGIN
	DELETE FROM bi_list
	WHERE TP_ID = old.ID; 
END;
CREATE TRIGGER remove_the_rest_of_st
BEFORE delete 
ON bi_list
BEGIN
	DELETE FROM st_list
	WHERE bi_id = old.ID; 
END;
COMMIT;
